[theme]
# Primary accent for interactive elements
primaryColor = "#115fd8"

# Background color for the main content area
backgroundColor = "#f8f9fa"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#e9ecef"

# Color used for almost all text
textColor = "#343a40"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"